/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'email' : string,
  'projectDetails' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'blobId' : string,
  'mediaType' : string,
  'category' : string,
  'serviceId' : [] | [bigint],
}
export interface Review {
  'id' : bigint,
  'clientName' : string,
  'createdAt' : bigint,
  'reviewText' : string,
  'clientProfileBlobId' : [] | [string],
  'rating' : bigint,
  'serviceId' : [] | [bigint],
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'icon' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : string,
  'rating' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPortfolio' : ActorMethod<
    [string, string, string, string, string, [] | [bigint]],
    bigint
  >,
  'createReview' : ActorMethod<
    [string, [] | [string], string, bigint, [] | [bigint]],
    bigint
  >,
  'createService' : ActorMethod<
    [string, string, string, string, number],
    bigint
  >,
  'deletePortfolio' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteSubmission' : ActorMethod<[bigint], undefined>,
  'filterPortfolioByCategory' : ActorMethod<[string], Array<PortfolioItem>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getService' : ActorMethod<[bigint], Service>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'listReviews' : ActorMethod<[], Array<Review>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'listSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'markAsRead' : ActorMethod<[bigint], undefined>,
  'submitContact' : ActorMethod<[string, string, string], bigint>,
  'toggleServiceAvailability' : ActorMethod<[bigint], undefined>,
  'updatePortfolio' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [bigint]],
    undefined
  >,
  'updateReview' : ActorMethod<
    [bigint, string, [] | [string], string, bigint, [] | [bigint]],
    undefined
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, string, string, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];